# 使用Python 3.12作为基础镜像
FROM flask_base:v1.0.0

# 设置工作目录
WORKDIR /zhyn

# 复制依赖和编译脚本
COPY requirements.txt .
# 安装Python依赖
RUN pip install --no-cache-dir -r requirements.txt

# 创建必要的目录
RUN mkdir -p \
    /zhyn/alarm_images \
    /zhyn/app \
    /zhyn/backups \
    /zhyn/config \
    /zhyn/logs \
    /zhyn/migrations \
    /zhyn/scripts \
    /zhyn/ssl \
    /zhyn/tests

# 复制业务代码
COPY app/ /zhyn/app/
COPY scripts/ /zhyn/scripts/
COPY config/ /zhyn/config/
COPY migrations/ /zhyn/migrations/
COPY run.py .
COPY start_api_server.py .
COPY start_web_app.py .
COPY wsgi.py .


# 设置环境变量
ENV PYTHONPATH=/zhyn
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# 暴露端口
EXPOSE 8000 8800

# 启动命令
CMD ["python", "run.py", "--no-ssl"]