[supervisord]
nodaemon=true
logfile=/zhyn/logs/supervisord.log

[program:web]
command=gunicorn -w 4 -b 0.0.0.0:8000 "app:create_web_app()"
autostart=true
autorestart=true
stdout_logfile=/zhyn/logs/web.log
stderr_logfile=/zhyn/logs/web_err.log

[program:api]
command=gunicorn -w 4 -b 0.0.0.0:8800 "app:create_api_app()"
autostart=true
autorestart=true
stdout_logfile=/zhyn/logs/api.log
stderr_logfile=/zhyn/logs/api_err.log