"""Add user login tracking fields

Revision ID: 391513dc1aaa
Revises: 
Create Date: 2025-04-19 10:45:22.076036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391513dc1aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=64), nullable=True))
        batch_op.alter_column('current_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('current_token',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('login_count')

    # ### end Alembic commands ###
