"""initial migration

Revision ID: f11a647ff26f
Revises: 
Create Date: 2025-03-28 22:18:40.600756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11a647ff26f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_number', sa.String(length=50), nullable=True),
    sa.Column('alarm_type', sa.String(length=100), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('camera_ip', sa.String(length=50), nullable=True),
    sa.Column('alarm_time', sa.DateTime(), nullable=True),
    sa.Column('alarm_image', sa.String(length=255), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processed_time', sa.DateTime(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirm_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='设备名称'),
    sa.Column('ip_address', sa.String(length=50), nullable=False, comment='设备IP地址'),
    sa.Column('access_key', sa.String(length=64), nullable=False, comment='设备访问密钥'),
    sa.Column('secret_key', sa.String(length=128), nullable=False, comment='设备密钥'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('key_value_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name_zh', sa.String(length=100), nullable=True),
    sa.Column('system_name_en', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('well_name', sa.String(length=128), nullable=False, comment='油井名称'),
    sa.Column('detection_type', sa.String(length=50), nullable=False, comment='检测类型'),
    sa.Column('camera_ip', sa.String(length=50), nullable=False, comment='摄像头IP'),
    sa.Column('camera_preset', sa.Integer(), nullable=False, comment='摄像头预置点'),
    sa.Column('pressure_range', sa.Float(), nullable=False, comment='压力表量程'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('current_token', sa.String(length=128), nullable=True),
    sa.Column('token_timestamp', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('system_config')
    op.drop_table('key_value_setting')
    op.drop_table('edge_devices')
    op.drop_table('alarms')
    # ### end Alembic commands ###
