api_server:
  host: 0.0.0.0
  port: 8800
application:
  allowed_extensions:
  - txt
  - pdf
  - png
  - jpg
  - jpeg
  - gif
  - csv
  - xlsx
  items_per_page: 20
  max_content_length: 16777216
  upload_folder: /zhyn/alarm_images
database:
  host: 127.0.0.1
  name: oilfield_web_db
  password: admin123_Youtian
  port: 5432
  user: guanliyuan
debug: true
debug_log_enabled: true
logging:
  backup_count: 20
  date_format: '%Y-%m-%d %H:%M:%S'
  db_log: db_init.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  main_log: oilfield.log
  max_bytes: 52428800
  path: /zhyn/logs
secret_key: 7b776530fe748a6542c924ff2971eeb3ebbb766b3af225983741b98e5b5f489c
security:
  remember_cookie_httponly: true
  remember_cookie_secure: true
  session_cookie_httponly: true
  session_cookie_secure: true
session:
  permanent_lifetime_days: 7
  token_expiration_days: 1
ssl:
  api_cert_file: /zhyn/ssl/api_cert.pem
  api_key_file: /zhyn/ssl/api_key.pem
  cert_file: /zhyn/ssl/web_cert.pem
  key_file: /zhyn/ssl/web_key.pem
web_server:
  host: 0.0.0.0
  port: 8000
