"""add camera username and password fields

Revision ID: 03ffca519cec
Revises: 
Create Date: 2025-04-22 10:04:26.043696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03ffca519cec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.alter_column('alarm_code',
               existing_type=sa.VARCHAR(length=50),
               comment='告警编号，如WELL001_QT001',
               existing_comment='告警编号，标识一类告警，如ALM202404190001',
               existing_nullable=False)
        batch_op.alter_column('alarm_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='告警发生时间',
               existing_nullable=True)
        batch_op.alter_column('last_report_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='最后一次上报时间',
               existing_nullable=True)
        batch_op.alter_column('processed_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='处理完成时间',
               existing_nullable=True)
        batch_op.alter_column('confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='确认时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.drop_index('ix_alarms_alarm_code')

    with op.batch_alter_table('edge_devices', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('key_value_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='设置ID，自增',
               existing_comment='设置ID，自增主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               comment='设置键名',
               existing_comment='设置键名，唯一',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_comment='设置描述',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('oil_wells', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment='位置',
               existing_comment='地理位置',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='状态：正常、维护中、停机',
               existing_comment='油井状态',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='描述',
               existing_comment='油井描述',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=255),
               comment='系统Logo URL',
               existing_comment='系统logo URL',
               existing_nullable=True)
        batch_op.alter_column('theme_color',
               existing_type=sa.VARCHAR(length=20),
               comment='主题颜色',
               existing_comment='系统主题颜色',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_username', sa.String(length=50), nullable=True, comment='摄像头登录用户名'))
        batch_op.add_column(sa.Column('camera_password', sa.String(length=100), nullable=True, comment='摄像头登录密码'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='修改时间',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               comment='是否是管理员',
               existing_comment='是否为管理员',
               existing_nullable=True)
        batch_op.alter_column('current_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=64),
               comment='当前TOKEN，可用于API认证',
               existing_comment='当前登录令牌',
               existing_nullable=True)
        batch_op.alter_column('token_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='令牌创建时间',
               existing_nullable=True)
        batch_op.alter_column('last_login_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('last_login_ip',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_comment='最后登录IP',
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['current_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('last_login_ip',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_comment='最后登录IP',
               existing_nullable=True)
        batch_op.alter_column('last_login_time',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('token_timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='令牌创建时间',
               existing_nullable=True)
        batch_op.alter_column('current_token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=512),
               comment='当前登录令牌',
               existing_comment='当前TOKEN，可用于API认证',
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               comment='是否为管理员',
               existing_comment='是否是管理员',
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='修改时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.drop_column('camera_password')
        batch_op.drop_column('camera_username')

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('theme_color',
               existing_type=sa.VARCHAR(length=20),
               comment='系统主题颜色',
               existing_comment='主题颜色',
               existing_nullable=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=255),
               comment='系统logo URL',
               existing_comment='系统Logo URL',
               existing_nullable=True)

    with op.batch_alter_table('oil_wells', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment='油井描述',
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment='油井状态',
               existing_comment='状态：正常、维护中、停机',
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               comment='地理位置',
               existing_comment='位置',
               existing_nullable=True)

    with op.batch_alter_table('key_value_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_comment='设置描述',
               existing_nullable=True)
        batch_op.alter_column('key',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               comment='设置键名，唯一',
               existing_comment='设置键名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='设置ID，自增主键',
               existing_comment='设置ID，自增',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('edge_devices', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('alarms', schema=None) as batch_op:
        batch_op.create_index('ix_alarms_alarm_code', ['alarm_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='更新时间',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('confirmed_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='确认时间',
               existing_nullable=True)
        batch_op.alter_column('processed_time',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='处理完成时间',
               existing_nullable=True)
        batch_op.alter_column('last_report_time',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='最后一次上报时间',
               existing_nullable=True)
        batch_op.alter_column('alarm_time',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='告警发生时间',
               existing_nullable=True)
        batch_op.alter_column('alarm_code',
               existing_type=sa.VARCHAR(length=50),
               comment='告警编号，标识一类告警，如ALM202404190001',
               existing_comment='告警编号，如WELL001_QT001',
               existing_nullable=False)

    # ### end Alembic commands ###
