"""Add system name settings

Revision ID: 896f3b60763b
Revises: 26b300b2cc6a
Create Date: 2025-03-06 21:21:36.607717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896f3b60763b'
down_revision = '26b300b2cc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name_zh', sa.String(length=128), nullable=True),
    sa.Column('system_name_en', sa.String(length=128), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('smtp_server', sa.String(length=128), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('sender_email', sa.String(length=128), nullable=True),
    sa.Column('email_password', sa.String(length=128), nullable=True),
    sa.Column('enable_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('system_setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.drop_table('settings')
    # ### end Alembic commands ###
