"""add confirm_type to alarm

Revision ID: 90213458cb73
Revises: 
Create Date: 2025-03-15 22:03:28.240814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90213458cb73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.drop_column('confirm_type')

    # ### end Alembic commands ###
